import React,{useEffect,useState} from 'react';import{Link}from'react-router-dom';import{ArrowRight,ArrowUpRight,ChevronRight,Heart,Leaf,Sparkles,Truck}from'lucide-react';import{api}from'../store.jsx';import{Benefits,Loader}from'../components/Layout.jsx';import{ProductCard}from'../components/ProductCard.jsx';
const categoryImages={'dinner-sets':'ceramic-dinner-set','plates-bowls':'sage-bowls','mugs-cups':'cups','cutlery':'cutlery','serveware':'wood-tray','table-decor':'serving-plate','glassware':'glass-jug','storage':'stoneware'};
export default function Home(){const[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{Promise.all([api('/categories'),api('/products?limit=8&featured=true')]).then(([c,p])=>{setCategories(c.categories);setProducts(p.products)}).catch(()=>{}).finally(()=>setLoading(false))},[]);return <>
 <section className="hero"><div className="container hero-grid"><div className="hero-text"><div className="eyebrow"><Leaf size={15}/> THE ART OF DINING</div><h1>Elevate your<br/><em>everyday dining.</em></h1><p>Beautiful tableware, warm conversations, and timeless pieces made for the moments that matter.</p><div className="hero-actions"><Link className="button primary" to="/shop">Shop Collection <ArrowRight size={17}/></Link><Link className="button ghost" to="/shop?category=dinner-sets">Explore Dinner Sets <ChevronRight size={17}/></Link></div><div className="hero-numbers"><span><b>{categories.reduce((t,c)=>t+Number(c.product_count||0),0)||'—'}</b><small>Curated Products</small></span><span><b>{categories.length||'—'}</b><small>Shop Categories</small></span><span><b>BD Wide</b><small>Delivery</small></span></div></div><div className="hero-visual"><div className="hero-image"><img src="/images/hero-tableware.webp" alt="Elegant sage green dinnerware styled on a dining table"/></div><div className="hero-floating"><Sparkles size={19}/><div><b>Thoughtful Details</b><small>Made for memorable meals</small></div></div><div className="hero-round">New<br/>Season<br/><span>2026</span></div></div></div></section>
 <div className="container"><Benefits/></div>
 <section className="section container"><div className="section-heading"><div><span className="section-kicker">DISCOVER YOUR STYLE</span><h2>Shop by Category</h2><p>Everything you need to set a beautiful table.</p></div><Link className="see-all" to="/shop">Explore all <ArrowRight size={16}/></Link></div><div className="category-grid">{(categories.length?categories:Object.keys(categoryImages).map(slug=>({slug,name:slug.replace('-',' & ')}))).map(cat=><Link className="category-tile" to={'/shop?category='+cat.slug} key={cat.slug}><div className="category-image"><img src={cat.image||`/images/${categoryImages[cat.slug]||'sage-bowls'}.webp`} alt={cat.name}/></div><strong>{cat.name}</strong><span>{cat.product_count??''} products</span></Link>)}</div></section>
 <section className="section container"><div className="section-heading"><div><span className="section-kicker">THE PIECES WE LOVE</span><h2>Featured Products</h2><p>Beautiful essentials, selected for your table.</p></div><Link className="see-all" to="/shop">View all products <ArrowRight size={16}/></Link></div>{loading?<Loader/>:<div className="products-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>}</section>
 <section className="container"><div className="promo-banner"><div className="promo-copy"><span className="section-kicker">GIVE YOUR TABLE A REFRESH</span><h2>Make every<br/><em>meal feel special.</em></h2><p>Discover pieces that bring warmth and character to your home.</p><Link to="/shop?sort=newest" className="button cream">Discover Collection <ArrowUpRight size={17}/></Link></div><div className="promo-image"><img src="/images/ceramic-dinner-set.webp" alt="Ceramic floral dinner set"/></div></div></section>
 <section className="section container story-section"><div className="story-image"><img src="/images/wood-tray.webp" alt="Warm wooden tray and table decor"/></div><div className="story-text"><span className="section-kicker">A BETTER WAY TO DINE</span><h2>Little things.<br/><em>Beautiful moments.</em></h2><p>From breakfast to family celebrations, the right tableware makes time together feel even better. We handpick practical pieces with a timeless look and a warmth you'll love coming home to.</p><div className="story-points"><span><Leaf size={18}/> Selected with care</span><span><Truck size={18}/> Delivered across Bangladesh</span><span><Heart size={18}/> Designed for everyday life</span></div><Link className="button outline" to="/shop">Explore Our Collection <ArrowRight size={17}/></Link></div></section>
 </>}
