import {query,tx} from './db.js';
import {requireAdmin} from './auth.js';
import {httpError} from './utils.js';
import {cancelOrderAndRestore} from './orders.js';
const slugify=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);
function productInput(b){const name=String(b.name||'').trim(),slug=slugify(b.slug||name),sku=String(b.sku||'').trim().slice(0,60),description=String(b.description||'').trim().slice(0,6000),image=String(b.image||'').trim().slice(0,1500),material=String(b.material||'').trim().slice(0,100),categoryId=String(b.categoryId||'');const basePrice=Number(b.basePrice),comparePrice=b.comparePrice==null||b.comparePrice===''?null:Number(b.comparePrice);if(name.length<3||name.length>160||!slug||!sku||!categoryId||!Number.isInteger(basePrice)||basePrice<0||comparePrice!=null&&(!Number.isInteger(comparePrice)||comparePrice<0))throw httpError(400,'Invalid product fields');const gallery=Array.isArray(b.gallery)?b.gallery.filter(x=>typeof x==='string'&&x.length<1500).slice(0,8):[];const tags=Array.isArray(b.tags)?b.tags.filter(x=>typeof x==='string').slice(0,12).map(x=>x.slice(0,40)):[];return {name,slug,sku,description,image,material,categoryId,basePrice,comparePrice,gallery,tags,active:b.active!==false,featured:!!b.featured}}
function variantInput(b){const name=String(b.name||'').trim(),sku=String(b.sku||'').trim(),price=Number(b.price),stock=Number(b.stock);if(!name||name.length>100||!sku||sku.length>80||!Number.isInteger(price)||price<0||!Number.isInteger(stock)||stock<0)throw httpError(400,'Invalid variant');return{name,sku,price,stock,options:typeof b.options==='object'&&b.options&&!Array.isArray(b.options)?b.options:{},active:b.active!==false}}
export function registerAdmin(app){
 app.get('/api/admin/dashboard',requireAdmin,async(req,res)=>{const [sales,orders,customers,products,recent,monthly,campaigns]=await Promise.all([query("SELECT COALESCE(SUM(total),0)::int total FROM orders WHERE payment_status='PAID' OR (payment_method='COD' AND status='DELIVERED')"),query("SELECT status,count(*)::int count FROM orders GROUP BY status"),query('SELECT count(*)::int count FROM users WHERE role=\'CUSTOMER\''),query('SELECT count(*)::int count FROM products WHERE active=true'),query('SELECT order_no,customer_name,total,status,created_at,payment_method FROM orders ORDER BY created_at DESC LIMIT 8'),query("SELECT to_char(date_trunc('month',created_at),'Mon YYYY') month,COALESCE(sum(total),0)::int total FROM orders WHERE payment_status='PAID' OR (payment_method='COD' AND status='DELIVERED') GROUP BY date_trunc('month',created_at) ORDER BY date_trunc('month',created_at) DESC LIMIT 6"),query("SELECT COALESCE(NULLIF(utm_campaign,''),'(direct)') campaign,count(*)::int orders,COALESCE(sum(total),0)::int order_value FROM orders GROUP BY 1 ORDER BY orders DESC LIMIT 8")]);res.json({revenue:sales.rows[0].total,orders:orders.rows,customers:customers.rows[0].count,products:products.rows[0].count,recent:recent.rows,sales:monthly.rows.reverse(),campaigns:campaigns.rows})});
 app.get('/api/admin/orders',requireAdmin,async(req,res)=>{const status=String(req.query.status||'');const {rows}=await query(`SELECT o.*,COALESCE((SELECT json_agg(json_build_object('name',i.product_name,'variant',i.variant_name,'quantity',i.quantity,'price',i.unit_price)) FROM order_items i WHERE i.order_id=o.id),'[]') items FROM orders o ${status?'WHERE o.status=$1':''} ORDER BY o.created_at DESC LIMIT 200`,status?[status]:[]);res.json({orders:rows.map(({tracking_token,...o})=>o)})});
 app.patch('/api/admin/orders/:id',requireAdmin,async(req,res)=>{const status=String(req.body.status||'');if(!['PENDING','CONFIRMED','PACKING','SHIPPED','DELIVERED','CANCELLED'].includes(status))throw httpError(400,'Invalid status');if(status==='CANCELLED'){const o=(await query('SELECT * FROM orders WHERE id=$1',[req.params.id])).rows[0];if(!o)throw httpError(404,'Order not found');if(o.payment_status==='PAID')throw httpError(409,'Refund payment externally before cancelling a paid order');await cancelOrderAndRestore(o.id);return res.json({ok:true})}const {rows}=await query(`UPDATE orders SET status=$1,payment_status=CASE WHEN payment_method='COD' AND $1='DELIVERED' THEN 'PAID' ELSE payment_status END,updated_at=now() WHERE id=$2 AND status<>'CANCELLED' AND (payment_method='COD' OR payment_status='PAID') RETURNING id`,[status,req.params.id]);if(!rows.length)throw httpError(409,'Paid confirmation required or order unavailable');res.json({ok:true})});
 app.get('/api/admin/products',requireAdmin,async(req,res)=>{const {rows}=await query("SELECT p.*,c.name category_name,COALESCE((SELECT json_agg(json_build_object('id',v.id,'name',v.name,'sku',v.sku,'price',v.price,'stock',v.stock,'active',v.active,'options',v.options) ORDER BY v.price) FROM variants v WHERE v.product_id=p.id),'[]') variants FROM products p JOIN categories c ON p.category_id=c.id ORDER BY p.created_at DESC");res.json({products:rows})});
 app.post('/api/admin/products',requireAdmin,async(req,res)=>{const p=productInput(req.body);const vs=(req.body.variants||[]).map(variantInput);if(!vs.length)throw httpError(400,'Add at least one product variant');const result=await tx(async c=>{const {rows}=await c.query('INSERT INTO products(category_id,name,slug,sku,description,image,material,base_price,compare_price,gallery,tags,active,featured) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13) RETURNING id',[p.categoryId,p.name,p.slug,p.sku,p.description,p.image,p.material,p.basePrice,p.comparePrice,JSON.stringify(p.gallery),p.tags,p.active,p.featured]);for(const v of vs)await c.query('INSERT INTO variants(product_id,name,sku,price,stock,options,active) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7)',[rows[0].id,v.name,v.sku,v.price,v.stock,JSON.stringify(v.options),v.active]);return rows[0]});res.status(201).json({product:result})});
 app.put('/api/admin/products/:id',requireAdmin,async(req,res)=>{const p=productInput(req.body);await query('UPDATE products SET category_id=$1,name=$2,slug=$3,sku=$4,description=$5,image=$6,material=$7,base_price=$8,compare_price=$9,gallery=$10::jsonb,tags=$11,active=$12,featured=$13 WHERE id=$14',[p.categoryId,p.name,p.slug,p.sku,p.description,p.image,p.material,p.basePrice,p.comparePrice,JSON.stringify(p.gallery),p.tags,p.active,p.featured,req.params.id]);res.json({ok:true})});
 app.patch('/api/admin/products/:id/status',requireAdmin,async(req,res)=>{const {rowCount}=await query('UPDATE products SET active=$1 WHERE id=$2',[!!req.body.active,req.params.id]);if(!rowCount)throw httpError(404,'Product not found');res.json({ok:true})});
 app.post('/api/admin/products/:id/variants',requireAdmin,async(req,res)=>{const v=variantInput(req.body);const {rows}=await query('INSERT INTO variants(product_id,name,sku,price,stock,options,active) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) RETURNING *',[req.params.id,v.name,v.sku,v.price,v.stock,JSON.stringify(v.options),v.active]);res.status(201).json({variant:rows[0]})});
 app.put('/api/admin/variants/:id',requireAdmin,async(req,res)=>{const v=variantInput(req.body);const {rows}=await query('UPDATE variants SET name=$1,sku=$2,price=$3,stock=$4,options=$5::jsonb,active=$6 WHERE id=$7 RETURNING *',[v.name,v.sku,v.price,v.stock,JSON.stringify(v.options),v.active,req.params.id]);if(!rows.length)throw httpError(404,'Variant not found');res.json({variant:rows[0]})});
 app.get('/api/admin/categories',requireAdmin,async(req,res)=>{const {rows}=await query('SELECT * FROM categories ORDER BY position,name');res.json({categories:rows})});
 app.post('/api/admin/categories',requireAdmin,async(req,res)=>{const name=String(req.body.name||'').trim(),slug=slugify(req.body.slug||name),image=String(req.body.image||'').slice(0,1500),position=Number(req.body.position||0);if(!name||!slug||!Number.isInteger(position))throw httpError(400,'Invalid category');const {rows}=await query('INSERT INTO categories(name,slug,image,position) VALUES($1,$2,$3,$4) RETURNING *',[name,slug,image,position]);res.status(201).json({category:rows[0]})});
 app.put('/api/admin/categories/:id',requireAdmin,async(req,res)=>{const name=String(req.body.name||'').trim(),slug=slugify(req.body.slug||name);if(!name||!slug)throw httpError(400,'Invalid category');const {rows}=await query('UPDATE categories SET name=$1,slug=$2,image=$3,position=$4 WHERE id=$5 RETURNING *',[name,slug,String(req.body.image||''),Number(req.body.position||0),req.params.id]);res.json({category:rows[0]})});
 app.get('/api/admin/coupons',requireAdmin,async(req,res)=>{const {rows}=await query('SELECT * FROM coupons ORDER BY code');res.json({coupons:rows})});
 app.post('/api/admin/coupons',requireAdmin,async(req,res)=>{const code=String(req.body.code||'').trim().toUpperCase(),type=String(req.body.type||''),value=Number(req.body.value),minSubtotal=Number(req.body.minSubtotal||0),maxUses=req.body.maxUses===null||req.body.maxUses===''?null:Number(req.body.maxUses);if(!/^[A-Z0-9_-]{3,30}$/.test(code)||!['PERCENT','FIXED'].includes(type)||!Number.isInteger(value)||value<1||type==='PERCENT'&&value>100||!Number.isInteger(minSubtotal)||minSubtotal<0||maxUses!=null&&(!Number.isInteger(maxUses)||maxUses<1))throw httpError(400,'Invalid coupon');const {rows}=await query('INSERT INTO coupons(code,type,value,min_subtotal,max_uses,expires_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[code,type,value,minSubtotal,maxUses,req.body.expiresAt||null]);res.status(201).json({coupon:rows[0]})});
 app.patch('/api/admin/coupons/:id',requireAdmin,async(req,res)=>{const {rows}=await query('UPDATE coupons SET active=$1 WHERE id=$2 RETURNING *',[!!req.body.active,req.params.id]);res.json({coupon:rows[0]})});
}
