import {randomBytes} from 'node:crypto';
import {query,tx} from './db.js';
import {httpError,shippingFor,discountFor} from './utils.js';
import {createSSLSession,releasePaymentReservation,querySSLSession,confirmSSLPayment} from './payments.js';
import {providerConfirmsNonPayment} from './payment-check.js';
import {requireAuth} from './auth.js';
import {sendOrderEmails} from './notifications.js';
const mkOrderNo=()=>`DH${Date.now().toString(36).toUpperCase()}${randomBytes(3).toString('hex').toUpperCase()}`;
const itemSelect=`SELECT v.id variant_id,v.product_id,v.name variant_name,v.sku,v.price,v.stock,v.active variant_active,p.name product_name,p.image,p.active product_active FROM variants v JOIN products p ON v.product_id=p.id WHERE v.id=$1`;
export function validateBasket(items){if(!Array.isArray(items)||items.length<1||items.length>30)throw httpError(400,'Choose 1–30 items');const ids=new Set();return items.map(it=>{const variantId=String(it.variantId||''),quantity=Number(it.quantity);if(!/^[0-9a-f-]{36}$/i.test(variantId)||!Number.isInteger(quantity)||quantity<1||quantity>20||ids.has(variantId))throw httpError(400,'Invalid or duplicate cart item');ids.add(variantId);return{variantId,quantity}})}
export async function quote(items,city,couponCode=''){const normalized=validateBasket(items);let subtotal=0;const resolved=[];for(const item of normalized){const {rows}=await query(itemSelect,[item.variantId]);const p=rows[0];if(!p||!p.variant_active||!p.product_active||p.stock<item.quantity)throw httpError(409,`An item is unavailable or has insufficient stock`);subtotal+=p.price*item.quantity;resolved.push({...p,quantity:item.quantity})}let coupon=null;if(couponCode){const {rows}=await query('SELECT * FROM coupons WHERE code=$1',[String(couponCode).toUpperCase().trim()]);coupon=rows[0]||null;if(!coupon||!coupon.active||subtotal<coupon.min_subtotal||coupon.expires_at&&new Date(coupon.expires_at)<new Date()||coupon.max_uses!=null&&coupon.used_count>=coupon.max_uses)throw httpError(400,'Coupon unavailable or cart minimum not met')}const discount=discountFor(coupon,subtotal),shipping=shippingFor(city);return {items:resolved,subtotal,discount,shipping,total:subtotal-discount+shipping,coupon}}
export async function cancelOrderAndRestore(orderId,paymentFailed=false){return tx(async c=>{const {rows}=await c.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[orderId]);const o=rows[0];if(!o||o.status==='CANCELLED'||o.payment_status==='PAID')return false;await c.query("UPDATE orders SET status='CANCELLED',payment_status=CASE WHEN payment_method='SSL' THEN 'FAILED' ELSE payment_status END,updated_at=now() WHERE id=$1",[orderId]);const {rows:items}=await c.query('SELECT * FROM order_items WHERE order_id=$1',[orderId]);for(const item of items)if(item.variant_id)await c.query('UPDATE variants SET stock=stock+$1 WHERE id=$2',[item.quantity,item.variant_id]);if(o.coupon_id)await c.query('UPDATE coupons SET used_count=GREATEST(0,used_count-1) WHERE id=$1',[o.coupon_id]);return true})}
export async function expireOldPayments(){
 const {rows}=await query("SELECT id,transaction_id,gateway_session_id FROM orders WHERE payment_method='SSL' AND payment_status='PENDING' AND payment_expires_at<now() LIMIT 100");
 for(const o of rows){
  try{
   if(!o.gateway_session_id){await cancelOrderAndRestore(o.id,true);continue}
   const status=await querySSLSession(o.gateway_session_id);
   if(['VALID','VALIDATED'].includes(String(status.status||'').toUpperCase())){
    if(status.val_id)await confirmSSLPayment({tran_id:o.transaction_id,val_id:status.val_id});
    else console.warn('Paid session needs manual reconciliation:',o.transaction_id);
   }else if(providerConfirmsNonPayment(status)){
    await cancelOrderAndRestore(o.id,true);
   }else console.warn('Payment remains pending/unverified, stock held:',o.transaction_id);
  }catch(e){console.error('Cannot reconcile expiring payment; stock remains held:',o.transaction_id,e.message)}
 }
}
const selectOrder=`SELECT o.*,COALESCE(json_agg(json_build_object('id',i.id,'productId',i.product_id,'variantId',i.variant_id,'name',i.product_name,'variant',i.variant_name,'sku',i.sku,'image',i.image,'price',i.unit_price,'quantity',i.quantity)) FILTER (WHERE i.id IS NOT NULL),'[]') AS items FROM orders o LEFT JOIN order_items i ON o.id=i.order_id`;
const publicOrder=o=>{if(!o)return null;const {tracking_token,transaction_id,gateway_val_id,gateway_session_id,...safe}=o;return safe};
export function registerOrders(app){
 app.post('/api/orders/quote',async(req,res)=>{const q=await quote(req.body.items,req.body.city,req.body.couponCode);res.json({subtotal:q.subtotal,discount:q.discount,shipping:q.shipping,total:q.total,items:q.items.map(x=>({variantId:x.variant_id,price:x.price,stock:x.stock}))})});
 app.post('/api/orders',async(req,res)=>{await expireOldPayments();const b=req.body||{};const name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),phone=String(b.phone||'').trim(),address=String(b.address||'').trim(),city=String(b.city||'').trim(),area=String(b.area||'').trim(),notes=String(b.notes||'').trim();const method=String(b.paymentMethod||'COD');if(name.length<2||name.length>100||!/^\S+@\S+\.\S+$/.test(email)||!/^[+0-9\-\s]{8,20}$/.test(phone)||address.length<8||address.length>300||!city||city.length>80||!area||area.length>80||notes.length>500||!['COD','SSL'].includes(method))throw httpError(400,'Complete valid delivery details are required');if(method==='SSL'&&process.env.SSL_ENABLED!=='true')throw httpError(503,'Online payment is not configured');const basket=validateBasket(b.items);const utm=b.utm&&typeof b.utm==='object'?b.utm:{};const utmVal=k=>String(utm[k]||'').trim().slice(0,120);
 const order=await tx(async c=>{let subtotal=0;const items=[];for(const it of basket){const {rows}=await c.query(itemSelect+' FOR UPDATE OF v',[it.variantId]);const p=rows[0];if(!p||!p.product_active||!p.variant_active)throw httpError(409,'A product is unavailable');const updated=await c.query('UPDATE variants SET stock=stock-$1 WHERE id=$2 AND stock>=$1 RETURNING id',[it.quantity,it.variantId]);if(!updated.rowCount)throw httpError(409,`${p.product_name} stock changed. Please update cart`);subtotal+=p.price*it.quantity;items.push({...p,quantity:it.quantity})}
 let coupon=null,discount=0;const code=String(b.couponCode||'').toUpperCase().trim();if(code){const {rows}=await c.query('SELECT * FROM coupons WHERE code=$1 FOR UPDATE',[code]);coupon=rows[0];discount=discountFor(coupon,subtotal);if(!coupon||!discount&&coupon.type==='FIXED'||!coupon.active||subtotal<coupon.min_subtotal||coupon.expires_at&&new Date(coupon.expires_at)<new Date()||coupon.max_uses!=null&&coupon.used_count>=coupon.max_uses)throw httpError(400,'Coupon no longer valid');await c.query('UPDATE coupons SET used_count=used_count+1 WHERE id=$1',[coupon.id])}
 const shipping=shippingFor(city),total=subtotal-discount+shipping,orderNo=mkOrderNo(),track=randomBytes(24).toString('hex');const tranId=method==='SSL'?`DH_${randomBytes(12).toString('hex')}`:null;const {rows}=await c.query(`INSERT INTO orders(order_no,user_id,tracking_token,customer_name,email,phone,address,city,area,notes,utm_source,utm_medium,utm_campaign,utm_content,subtotal,discount,shipping,total,coupon_id,payment_method,payment_status,transaction_id,payment_expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23) RETURNING *`,[orderNo,req.user?.id||null,track,name,email,phone,address,city,area,notes,utmVal('utm_source'),utmVal('utm_medium'),utmVal('utm_campaign'),utmVal('utm_content'),subtotal,discount,shipping,total,coupon?.id||null,method,method==='SSL'?'PENDING':'UNPAID',tranId,method==='SSL'?new Date(Date.now()+30*60*1000):null]);for(const i of items)await c.query('INSERT INTO order_items(order_id,product_id,variant_id,product_name,variant_name,sku,image,unit_price,quantity) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[rows[0].id,i.product_id,i.variant_id,i.product_name,i.variant_name,i.sku,i.image,i.price,i.quantity]);return rows[0]});
 if(method==='SSL'){try{const paymentUrl=await createSSLSession(order);res.status(201).json({orderNo:order.order_no,trackingToken:order.tracking_token,redirectUrl:paymentUrl,paymentMethod:'SSL'})}catch(e){await releasePaymentReservation(order.id);throw httpError(502,'Unable to initialize secure payment. No payment was taken; cart items were released.')}}else {res.status(201).json({orderNo:order.order_no,trackingToken:order.tracking_token,paymentMethod:'COD'});void sendOrderEmails(order.order_no).catch(e=>console.error('Order email:',e.message))}
 });
 app.post('/api/orders/track',async(req,res)=>{const orderNo=String(req.body.orderNo||'').trim(),token=String(req.body.trackingToken||''),phone=String(req.body.phone||'');if(!orderNo||!token&&!phone)throw httpError(400,'Order ID and phone or tracking token required');const {rows}=await query(`${selectOrder} WHERE o.order_no=$1 AND (o.tracking_token=$2 OR o.phone=$3) GROUP BY o.id`,[orderNo,token,phone]);if(!rows.length)throw httpError(404,'Order not found');res.json({order:publicOrder(rows[0])})});
 app.get('/api/orders/mine',requireAuth,async(req,res)=>{const {rows}=await query(`${selectOrder} WHERE o.user_id=$1 GROUP BY o.id ORDER BY o.created_at DESC LIMIT 100`,[req.user.id]);res.json({orders:rows.map(publicOrder)})});
}
