import {query,tx} from './db.js';
import {httpError} from './utils.js';
import {matchesPayment} from './payment-check.js';
import {sendOrderEmails} from './notifications.js';
const gateway=()=>process.env.SSL_SANDBOX==='false'?'https://securepay.sslcommerz.com':'https://sandbox.sslcommerz.com';
const credentials=()=>{if(process.env.SSL_ENABLED!=='true'||!process.env.SSL_STORE_ID||!process.env.SSL_STORE_PASSWORD)throw httpError(503,'SSLCommerz merchant configuration is missing');return {store_id:process.env.SSL_STORE_ID,store_passwd:process.env.SSL_STORE_PASSWORD}};
export async function createSSLSession(order){const url=process.env.API_PUBLIC_URL;if(!url||!/^https?:\/\//.test(url))throw httpError(503,'API_PUBLIC_URL must be set');const params=new URLSearchParams({...credentials(),total_amount:(order.total).toFixed(2),currency:'BDT',tran_id:order.transaction_id,success_url:`${url}/api/payments/ssl/success`,fail_url:`${url}/api/payments/ssl/fail`,cancel_url:`${url}/api/payments/ssl/cancel`,ipn_url:`${url}/api/payments/ssl/ipn`,shipping_method:'Courier',product_name:'Dining essentials',product_category:'Dinnerware',product_profile:'general',cus_name:order.customer_name,cus_email:order.email,cus_add1:order.address,cus_city:order.city,cus_country:'Bangladesh',cus_phone:order.phone,ship_name:order.customer_name,ship_add1:order.address,ship_city:order.city,ship_postcode:'1200',ship_country:'Bangladesh',value_a:order.order_no});const response=await fetch(`${gateway()}/gwprocess/v4/api.php`,{method:'POST',body:params,signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('SSL session rejected');const data=await response.json();if(!data.GatewayPageURL||!data.status||data.status.toUpperCase()!=='SUCCESS')throw Error('No payment session created');await query('UPDATE orders SET gateway_session_id=$1 WHERE id=$2',[data.sessionkey||null,order.id]);return data.GatewayPageURL}
export async function releasePaymentReservation(id){const {cancelOrderAndRestore}=await import('./orders.js');return cancelOrderAndRestore(id,true)}
export async function querySSLSession(sessionkey){
 const u=new URL(`${gateway()}/validator/api/merchantTransIDvalidationAPI.php`);
 for(const [k,v] of Object.entries({...credentials(),sessionkey,format:'json'}))u.searchParams.set(k,v);
 const response=await fetch(u,{signal:AbortSignal.timeout(15000)});
 if(!response.ok)throw Error('Merchant transaction status lookup unavailable');
 return response.json();
}
export async function validatePayment(valId){const u=new URL(`${gateway()}/validator/api/validationserverAPI.php`);const c=credentials();for(const [k,v] of Object.entries({...c,val_id:valId,format:'json'}))u.searchParams.set(k,v);const response=await fetch(u,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Payment validation endpoint unavailable');return response.json()}
export async function confirmSSLPayment(body){const tranId=String(body.tran_id||'').slice(0,100),valId=String(body.val_id||'').slice(0,100);if(!tranId||!valId)throw httpError(400,'Missing payment identifiers');const {rows}=await query('SELECT * FROM orders WHERE transaction_id=$1',[tranId]);const order=rows[0];if(!order||order.payment_method!=='SSL')throw httpError(404,'Unknown transaction');const result=await validatePayment(valId);const ok=matchesPayment(result,order,process.env.SSL_STORE_ID);if(!ok)throw httpError(400,'Payment verification mismatch');let newlyPaid=false;await tx(async c=>{const {rows:locked}=await c.query('SELECT payment_status,status FROM orders WHERE id=$1 FOR UPDATE',[order.id]);if(locked[0].payment_status==='PAID')return;if(locked[0].status==='CANCELLED')throw httpError(409,'Order expired before payment was confirmed; contact support');newlyPaid=true;await c.query("UPDATE orders SET payment_status='PAID',status='CONFIRMED',gateway_val_id=$1,updated_at=now() WHERE id=$2",[valId,order.id])});if(newlyPaid)void sendOrderEmails(order.order_no,'paid').catch(e=>console.error('Payment email:',e.message));return order.order_no}
export function registerPayments(app){const web=()=>process.env.WEB_ORIGIN?.split(',')[0]?.replace(/\/$/,'')||'http://localhost:5173';
 app.post('/api/payments/ssl/ipn',async(req,res)=>{try{if(req.body?.val_id){await confirmSSLPayment(req.body)}res.json({received:true})}catch(e){console.error('SSL IPN verification failed:',e.message);res.status(400).json({received:false})}});
 app.all('/api/payments/ssl/success',async(req,res)=>{try{const orderNo=await confirmSSLPayment({...req.query,...req.body});res.redirect(303,`${web()}/order-success?order=${encodeURIComponent(orderNo)}&payment=success`)}catch(e){console.error('SSL payment callback:',e.message);res.redirect(303,`${web()}/payment-result?status=pending`)}});
 app.all('/api/payments/ssl/fail',(req,res)=>res.redirect(303,`${web()}/payment-result?status=failed`));
 app.all('/api/payments/ssl/cancel',(req,res)=>res.redirect(303,`${web()}/payment-result?status=cancelled`));
}
