import {query} from './db.js';
import {httpError} from './utils.js';
import {requireAuth} from './auth.js';
const base=`SELECT p.*,c.name category_name,c.slug category_slug,COALESCE((SELECT json_agg(json_build_object('id',v.id,'name',v.name,'sku',v.sku,'options',v.options,'price',v.price,'stock',v.stock,'active',v.active) ORDER BY v.price ASC) FROM variants v WHERE v.product_id=p.id AND v.active),'[]') variants,(SELECT ROUND(AVG(r.rating)::numeric,1) FROM reviews r WHERE r.product_id=p.id) rating,(SELECT COUNT(*)::int FROM reviews r WHERE r.product_id=p.id) review_count FROM products p JOIN categories c ON p.category_id=c.id`;
export function registerStore(app){
 app.get('/api/health',async(req,res)=>{await query('SELECT 1');res.json({status:'ok',service:'dinehub-api'})});
 app.get('/api/categories',async(req,res)=>{const {rows}=await query('SELECT c.*, (SELECT count(*)::int FROM products p WHERE p.category_id=c.id AND p.active) product_count FROM categories c ORDER BY c.position,c.name');res.json({categories:rows})});
 app.get('/api/products',async(req,res)=>{const q=String(req.query.q||'').trim().slice(0,100),category=String(req.query.category||''),material=String(req.query.material||''),sort=String(req.query.sort||'featured'),featured=req.query.featured==='true',min=Number(req.query.min||0),max=Number(req.query.max||10000000),page=Math.max(1,Math.min(1000,Number.parseInt(req.query.page)||1)),limit=Math.max(1,Math.min(48,Number.parseInt(req.query.limit)||12));const conditions=['p.active=true'],args=[];function add(sql,v){args.push(v);conditions.push(sql.replaceAll('?',`$${args.length}`))}if(q){args.push(`%${q}%`);conditions.push(`(p.name ILIKE $${args.length} OR p.description ILIKE $${args.length})`)}if(category)add('c.slug=?',category);if(material)add('p.material ILIKE ?',material);if(featured)conditions.push('p.featured=true');if(Number.isFinite(min)&&min>0)add('p.base_price>=?',min);if(Number.isFinite(max)&&max<10000000)add('p.base_price<=?',max);const order={'featured':'p.featured DESC,p.created_at DESC','newest':'p.created_at DESC','price-asc':'p.base_price ASC','price-desc':'p.base_price DESC','name':'p.name ASC'}[sort]||'p.featured DESC,p.created_at DESC';const filter=conditions.join(' AND ');const count=(await query(`SELECT count(*)::int n FROM products p JOIN categories c ON c.id=p.category_id WHERE ${filter}`,args)).rows[0].n;const {rows}=await query(`${base} WHERE ${filter} ORDER BY ${order} LIMIT $${args.length+1} OFFSET $${args.length+2}`,[...args,limit,(page-1)*limit]);res.json({products:rows,pagination:{page,limit,total:count,pages:Math.ceil(count/limit)}})});
 app.post('/api/products/by-ids',async(req,res)=>{const ids=Array.isArray(req.body.ids)?req.body.ids.filter(id=>/^[a-f0-9-]{36}$/i.test(id)).slice(0,100):[];if(!ids.length)return res.json({products:[]});const {rows}=await query(`${base} WHERE p.id=ANY($1::uuid[]) AND p.active=true`,[ids]);res.json({products:rows})});
 app.get('/api/products/:slug',async(req,res)=>{const {rows}=await query(`${base} WHERE p.slug=$1 AND p.active=true`,[req.params.slug]);if(!rows[0])throw httpError(404,'Product not found');const reviews=await query('SELECT r.rating,r.comment,r.created_at,u.name FROM reviews r JOIN users u ON r.user_id=u.id WHERE r.product_id=$1 ORDER BY r.created_at DESC LIMIT 30',[rows[0].id]);res.json({product:rows[0],reviews:reviews.rows})});
 app.get('/api/wishlist',requireAuth,async(req,res)=>{const {rows}=await query('SELECT product_id FROM wishlists WHERE user_id=$1',[req.user.id]);res.json({productIds:rows.map(x=>x.product_id)})});
 app.put('/api/wishlist/:productId',requireAuth,async(req,res)=>{await query('INSERT INTO wishlists(user_id,product_id) SELECT $1,id FROM products WHERE id=$2 ON CONFLICT DO NOTHING',[req.user.id,req.params.productId]);res.json({ok:true})});
 app.delete('/api/wishlist/:productId',requireAuth,async(req,res)=>{await query('DELETE FROM wishlists WHERE user_id=$1 AND product_id=$2',[req.user.id,req.params.productId]);res.json({ok:true})});
 app.post('/api/products/:id/reviews',requireAuth,async(req,res)=>{const rating=Number(req.body.rating),comment=String(req.body.comment||'').trim();if(!Number.isInteger(rating)||rating<1||rating>5||comment.length>1000)throw httpError(400,'Invalid review');const eligible=await query("SELECT 1 FROM order_items i JOIN orders o ON i.order_id=o.id WHERE o.user_id=$1 AND i.product_id=$2 AND o.status='DELIVERED' LIMIT 1",[req.user.id,req.params.id]);if(!eligible.rowCount)throw httpError(403,'Reviews require a delivered purchase');await query('INSERT INTO reviews(user_id,product_id,rating,comment) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,product_id) DO UPDATE SET rating=$3,comment=$4,created_at=now()',[req.user.id,req.params.id,rating,comment]);res.status(201).json({ok:true})});
}
