import React,{useEffect,useState} from 'react';
import {Link,NavLink,useNavigate} from 'react-router-dom';
import {Heart,ShoppingBag,UserRound,Search,Menu,X,Leaf,Instagram,Facebook,ChevronRight,Truck,ShieldCheck,PackageCheck,ArrowUpRight} from 'lucide-react';
import {api,useStore} from '../store.jsx';
const links=[['All Categories','/shop'],['Dinnerware','/shop?category=dinner-sets'],['Plates & Bowls','/shop?category=plates-bowls'],['Mugs & Cups','/shop?category=mugs-cups'],['Cutlery','/shop?category=cutlery'],['Glassware','/shop?category=glassware'],['Table Decor','/shop?category=table-decor'],['Serveware','/shop?category=serveware']];
export function Logo(){return <Link to="/" className="logo"><span className="logo-icon"><Leaf size={29}/></span><span><b>DineHub</b><small>Dining for a Better Home</small></span></Link>}
export function Header(){const [menu,setMenu]=useState(false),[term,setTerm]=useState(''),[navLinks,setNavLinks]=useState(links);useEffect(()=>{api('/categories').then(d=>setNavLinks([['All Categories','/shop'],...d.categories.map(c=>[c.name,'/shop?category='+c.slug])])).catch(()=>{})},[]);const navigate=useNavigate(),{cartCount,wishlist,user}=useStore();return <><div className="topbar"><span>Free shipping on select offers · Curated tableware for every home</span><span className="topbar-right">Nationwide Delivery <span className="sep">·</span> Order Hotline: 09600-000000</span></div><header className="header"><div className="container header-inner"><button className="icon-btn mobile-nav" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><Logo/><form className="searchbar" onSubmit={e=>{e.preventDefault();navigate('/shop?q='+encodeURIComponent(term));setMenu(false)}}><input placeholder="Search plates, bowls, cutlery, glassware..." value={term} onChange={e=>setTerm(e.target.value)} aria-label="Search products"/><button type="submit" aria-label="Search"><Search size={19}/></button></form><div className="header-actions"><Link className="header-action" to="/wishlist"><Heart size={21}/><span>Wishlist</span>{wishlist.length>0&&<em>{wishlist.length}</em>}</Link><Link className="header-action" to="/cart"><ShoppingBag size={21}/><span>Cart</span>{cartCount>0&&<em>{cartCount}</em>}</Link><Link className="header-action" to={user?user.role==='ADMIN'?'/admin':'/account':'/login'}><UserRound size={21}/><span>{user?'Account':'Log in'}</span></Link></div></div><nav className={'nav '+(menu?'nav-open':'')}><div className="container nav-items">{navLinks.map(([name,to])=><NavLink key={name} onClick={()=>setMenu(false)} to={to}>{name}</NavLink>)}<Link className="nav-offer" onClick={()=>setMenu(false)} to="/shop?sort=price-asc">Special Offers <ArrowUpRight size={14}/></Link></div></nav></header></>}
export function Footer(){return <footer className="footer"><div className="container footer-grid"><div><Logo/><p>Thoughtfully selected dining and kitchen essentials that make every meal feel special.</p><div className="social"><a href="https://instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={18}/></a><a href="https://facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook size={18}/></a></div></div><div><h4>Explore</h4><Link to="/shop">Shop all products</Link><Link to="/shop?category=dinner-sets">Dinner Sets</Link><Link to="/shop?category=plates-bowls">Plates & Bowls</Link><Link to="/wishlist">My Wishlist</Link></div><div><h4>Customer Care</h4><Link to="/track">Track Your Order</Link><Link to="/account">My Account</Link><a href="mailto:support@yourstore.example">Customer Support</a><Link to="/returns">Returns & Refunds</Link><Link to="/shipping">Shipping & Delivery</Link><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms & Conditions</Link></div><div><h4>Stay Inspired</h4><p>Beautiful tables and even better moments.</p><div className="contact">Dhaka, Bangladesh<br/>Nationwide delivery available</div></div></div><div className="container footer-bottom">© {new Date().getFullYear()} DineHub. All rights reserved. <span>Demo brand · Replace images, policies and contact info before launch</span></div></footer>}
export function Benefits(){return <div className="benefits"><div><Leaf size={22}/><span><b>Premium Quality</b><small>Durable & Long Lasting</small></span></div><div><PackageCheck size={22}/><span><b>Safe Packaging</b><small>Hassle Free Delivery</small></span></div><div><Truck size={22}/><span><b>Cash on Delivery</b><small>All over Bangladesh</small></span></div><div><ShieldCheck size={22}/><span><b>Secure Payment</b><small>SSLCommerz Ready</small></span></div></div>}
export function PageTitle({title,crumb}){return <div className="page-title"><div className="container"><div className="breadcrumb"><Link to="/">Home</Link><ChevronRight size={13}/><span>{crumb||title}</span></div><h1>{title}</h1></div></div>}
export function Empty({icon=ShoppingBag,title,description,action='/shop',actionLabel='Browse Products'}){const Icon=icon;return <div className="empty"><div className="empty-icon"><Icon size={36}/></div><h2>{title}</h2><p>{description}</p><Link className="button primary" to={action}>{actionLabel}</Link></div>}
export function Loader(){return <div className="loader"><div className="spinner"/>Loading...</div>}
